/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'audit-logs': RouteRecordInfo<'audit-logs', '/audit-logs', Record<never, never>, Record<never, never>>,
    'banks': RouteRecordInfo<'banks', '/banks', Record<never, never>, Record<never, never>>,
    'blacklist': RouteRecordInfo<'blacklist', '/blacklist', Record<never, never>, Record<never, never>>,
    'case-report': RouteRecordInfo<'case-report', '/case-report', Record<never, never>, Record<never, never>>,
    'conversion-reports': RouteRecordInfo<'conversion-reports', '/conversion-reports', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'deposits-all': RouteRecordInfo<'deposits-all', '/deposits/all', Record<never, never>, Record<never, never>>,
    'deposits-converted': RouteRecordInfo<'deposits-converted', '/deposits/converted', Record<never, never>, Record<never, never>>,
    'deposits-pending': RouteRecordInfo<'deposits-pending', '/deposits/pending', Record<never, never>, Record<never, never>>,
    'developer': RouteRecordInfo<'developer', '/developer', Record<never, never>, Record<never, never>>,
    'fund-storage-id': RouteRecordInfo<'fund-storage-id', '/fund-storage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'fund-storages': RouteRecordInfo<'fund-storages', '/fund-storages', Record<never, never>, Record<never, never>>,
    'intermediaries': RouteRecordInfo<'intermediaries', '/intermediaries', Record<never, never>, Record<never, never>>,
    'intermediary-case-id': RouteRecordInfo<'intermediary-case-id', '/intermediary-case/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'intermediary-cases': RouteRecordInfo<'intermediary-cases', '/intermediary-cases', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'merchant-case-id': RouteRecordInfo<'merchant-case-id', '/merchant-case/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'merchant-cases': RouteRecordInfo<'merchant-cases', '/merchant-cases', Record<never, never>, Record<never, never>>,
    'merchant-reports': RouteRecordInfo<'merchant-reports', '/merchant-reports', Record<never, never>, Record<never, never>>,
    'merchants': RouteRecordInfo<'merchants', '/merchants', Record<never, never>, Record<never, never>>,
    'operations': RouteRecordInfo<'operations', '/operations', Record<never, never>, Record<never, never>>,
    'partner-id': RouteRecordInfo<'partner-id', '/partner/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'partner-net': RouteRecordInfo<'partner-net', '/partner-net', Record<never, never>, Record<never, never>>,
    'pay-token': RouteRecordInfo<'pay-token', '/pay/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'player-risk': RouteRecordInfo<'player-risk', '/player-risk', Record<never, never>, Record<never, never>>,
    'reports': RouteRecordInfo<'reports', '/reports', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'status': RouteRecordInfo<'status', '/status', Record<never, never>, Record<never, never>>,
    'system-logs': RouteRecordInfo<'system-logs', '/system/logs', Record<never, never>, Record<never, never>>,
    'team-case-id': RouteRecordInfo<'team-case-id', '/team-case/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'team-cases': RouteRecordInfo<'team-cases', '/team-cases', Record<never, never>, Record<never, never>>,
    'team-reports': RouteRecordInfo<'team-reports', '/team-reports', Record<never, never>, Record<never, never>>,
    'teams': RouteRecordInfo<'teams', '/teams', Record<never, never>, Record<never, never>>,
    'two-factor': RouteRecordInfo<'two-factor', '/two-factor', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'wallet-transactions': RouteRecordInfo<'wallet-transactions', '/wallet-transactions', Record<never, never>, Record<never, never>>,
    'wallets': RouteRecordInfo<'wallets', '/wallets', Record<never, never>, Record<never, never>>,
    'withdrawals-all': RouteRecordInfo<'withdrawals-all', '/withdrawals/all', Record<never, never>, Record<never, never>>,
    'withdrawals-pending': RouteRecordInfo<'withdrawals-pending', '/withdrawals/pending', Record<never, never>, Record<never, never>>,
    'withdrawals-receipt-review': RouteRecordInfo<'withdrawals-receipt-review', '/withdrawals/receipt-review', Record<never, never>, Record<never, never>>,
  }
}
